name: ExcellenceEntertainment
favicon: null
layout_spectrum: 0.9366119906771928
typography_spectrum: 0.2181507635395974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.76928904466331
  lightness: 0.4245165893808007
  saturation: 0.9379459952469915
  rhythmicContrast: 0.4159020227380097
purpose: []
