name: ExcellenceEntertainment
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2181507635395974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#28282a'
    - '#dbdad8'
    - '#80888b'
  brandStrength: 0.76928904466331
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
