favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7795699
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#28282a'
    - '#dbdad8'
    - '#80888b'
  rhythmicContrast: 1
typography_spectrum: 0.74603
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: ExcellenceEntertainment
